environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4.4.1"
    - nodejs_version: "5.9.1"
matrix:
  allow_failures:
    - nodejs_version: "5.9.1"
  fast_finish: true
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
version: "{build}"
